FROM google/cloud-sdk
RUN curl -O  https://storage.googleapis.com/golang/go1.8.5.linux-amd64.tar.gz
RUN tar -C /usr/local -xf /go1.8.5.linux-amd64.tar.gz
RUN rm -f /go1.8.5.linux-amd64.tar.gz
ENV GOPATH /go
ENV PATH $PATH:/usr/local/go/bin
ENTRYPOINT ["/bin/bash"]
