kind: Service
apiVersion: v1
metadata:
  name: {{ template "bigquery-exporter.fullname" . }}
  labels:
    chart: {{ template "bigquery-exporter.chart" . }}
    app: {{ template "bigquery-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: exporter
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "bigquery-exporter.name" . }}
    release: "{{ .Release.Name }}"
