gauge_queries:
  - query:
    file: "/queries/metric1_name.sql"
    #refresh "*/5 * * * *" #every 5 minutes by default
counter_queries:
  - query:
    file: "/queries/metric2_name.sql"
    #refresh "30 9 * * *" #every day at 9:30