name: "Build, push, and deploy"
on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  build_image:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:prometheus-bigquery-exporter"
          file: ./dockerfile
          platforms: linux/amd64
          push: "{{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
          tags: |
            datawiredev/prometheus-bigquery-exporter:${{ github.sha }}
          cache-from: |
            type=gha,scope=refs/heads/main
            type=gha,scope=prometheus-bigquery-exporter-${{github.ref}}
          cache-to: type=gha,mode=max,scope=prometheus-bigquery-exporter-${{github.ref}}
